# Generated by Django 3.2.18 on 2023-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
